---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list 
# of plays, with each play being a dictionary
-

  # Hosts: where our play will run and options it will run with
  hosts: centos1
  gather_facts: False

  # Vars: variables that will apply to the play, on all target systems

  # Tasks: the list of tasks that will be executed within the play, this section
  #       can also be used for pre and post tasks

  vars:
    myval: "this is myVal variable"
    dict:
      example_key: example value
      dict_key: trying out things

  tasks:
    - name: Test dictionary key value
      debug:
        msg: "{{ dict }}"

    - name: Test named dictionry key value  with dot notation
      debug: 
       msg: "{{ dict.example_key }}"
    
    - name:  test name dcitionary with python brackets
      debug:
        msg: "{{ dict['dict_key'] }}"

    - name: testing myval
      debug:
        msg: "{{ myval }}"

  # Handlers: the list of handlers that are executed as a notify key from a task

  # Roles: list of roles to be imported into the play

# Three dots indicate the end of a YAML document
...
